{-
   Berlin Clock API
   API für die Berechnung und Darstellung der Berliner Uhr.

   The version of the OpenAPI document: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Default exposing
    ( berlinClockGet
    , timeGet
    )

import Api.Api as Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


{-| Liefert den aktuellen Status der Berliner Uhr.
-}
berlinClockGet : Api.Request Api.Data.BerlinClockState
berlinClockGet =
    Api.request
        "GET"
        "/berlin-clock"
        []
        []
        []
        Nothing
        Api.Data.berlinClockStateDecoder


{-| Liefert die aktuelle Uhrzeit des Systems.
-}
timeGet : Api.Request Api.Data.TimeResponse
timeGet =
    Api.request
        "GET"
        "/time"
        []
        []
        []
        Nothing
        Api.Data.timeResponseDecoder

