// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Berlin Clock API
 *
 * API für die Berechnung und Darstellung der Berliner Uhr.
 *
 * API version: 1.0.0
 */

package api

import (
	"context"
	"net/http"
	"errors"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() *DefaultAPIService {
	return &DefaultAPIService{}
}

// TimeGet - Liefert die aktuelle Uhrzeit des Systems.
func (s *DefaultAPIService) TimeGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update TimeGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TimeResponse{}) or use other options such as http.Ok ...
	// return Response(200, TimeResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("TimeGet method not implemented")
}

// BerlinClockGet - Liefert den aktuellen Status der Berliner Uhr.
func (s *DefaultAPIService) BerlinClockGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update BerlinClockGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, BerlinClockState{}) or use other options such as http.Ok ...
	// return Response(200, BerlinClockState{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BerlinClockGet method not implemented")
}
