// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Berlin Clock API
 *
 * API für die Berechnung und Darstellung der Berliner Uhr.
 *
 * API version: 1.0.0
 */

package api

import (
	"net/http"
	"strings"
)

// DefaultAPIController binds http requests to an api service and writes the service results to the http response
type DefaultAPIController struct {
	service DefaultAPIServicer
	errorHandler ErrorHandler
}

// DefaultAPIOption for how the controller is set up.
type DefaultAPIOption func(*DefaultAPIController)

// WithDefaultAPIErrorHandler inject ErrorHandler into controller
func WithDefaultAPIErrorHandler(h ErrorHandler) DefaultAPIOption {
	return func(c *DefaultAPIController) {
		c.errorHandler = h
	}
}

// NewDefaultAPIController creates a default api controller
func NewDefaultAPIController(s DefaultAPIServicer, opts ...DefaultAPIOption) *DefaultAPIController {
	controller := &DefaultAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultAPIController
func (c *DefaultAPIController) Routes() Routes {
	return Routes{
		"TimeGet": Route{
			"TimeGet",
			strings.ToUpper("Get"),
			"/time",
			c.TimeGet,
		},
		"BerlinClockGet": Route{
			"BerlinClockGet",
			strings.ToUpper("Get"),
			"/berlin-clock",
			c.BerlinClockGet,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the DefaultAPIController
func (c *DefaultAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"TimeGet",
			strings.ToUpper("Get"),
			"/time",
			c.TimeGet,
		},
		Route{
			"BerlinClockGet",
			strings.ToUpper("Get"),
			"/berlin-clock",
			c.BerlinClockGet,
		},
	}
}



// TimeGet - Liefert die aktuelle Uhrzeit des Systems.
func (c *DefaultAPIController) TimeGet(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.TimeGet(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// BerlinClockGet - Liefert den aktuellen Status der Berliner Uhr.
func (c *DefaultAPIController) BerlinClockGet(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.BerlinClockGet(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
