// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Berlin Clock API
 *
 * API für die Berechnung und Darstellung der Berliner Uhr.
 *
 * API version: 1.0.0
 */

package api




// BerlinClockState - Darstellung aller 5 Reihen der Berliner Uhr.
type BerlinClockState struct {

	SecondsLamp string `json:"secondsLamp,omitempty"`

	FiveHoursRow []string `json:"fiveHoursRow,omitempty"`

	SingleHoursRow []string `json:"singleHoursRow,omitempty"`

	FiveMinutesRow []string `json:"fiveMinutesRow,omitempty"`

	SingleMinutesRow []string `json:"singleMinutesRow,omitempty"`
}

// AssertBerlinClockStateRequired checks if the required fields are not zero-ed
func AssertBerlinClockStateRequired(obj BerlinClockState) error {
	return nil
}

// AssertBerlinClockStateConstraints checks if the values respects the defined constraints
func AssertBerlinClockStateConstraints(obj BerlinClockState) error {
	return nil
}
