{-
   Berlin Clock API
   API für die Berechnung und Darstellung der Berliner Uhr.

   The version of the OpenAPI document: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Data exposing
    ( BerlinClockState, BerlinClockStateSecondsLamp(..), berlinClockStateSecondsLampVariants, BerlinClockStateFiveHoursRow(..), berlinClockStateFiveHoursRowVariants, BerlinClockStateSingleHoursRow(..), berlinClockStateSingleHoursRowVariants, BerlinClockStateFiveMinutesRow(..), berlinClockStateFiveMinutesRowVariants, BerlinClockStateSingleMinutesRow(..), berlinClockStateSingleMinutesRowVariants
    , TimeResponse
    , encodeBerlinClockState
    , encodeTimeResponse
    , berlinClockStateDecoder
    , timeResponseDecoder
    )

import Api
import Dict
import Json.Decode
import Json.Encode


-- MODEL


{-| Darstellung aller 5 Reihen der Berliner Uhr.
-}
type alias BerlinClockState =
    { secondsLamp : Maybe BerlinClockStateSecondsLamp
    , fiveHoursRow : Maybe ( List BerlinClockStateFiveHoursRow )
    , singleHoursRow : Maybe ( List BerlinClockStateSingleHoursRow )
    , fiveMinutesRow : Maybe ( List BerlinClockStateFiveMinutesRow )
    , singleMinutesRow : Maybe ( List BerlinClockStateSingleMinutesRow )
    }


type BerlinClockStateSecondsLamp
    = BerlinClockStateSecondsLampY
    | BerlinClockStateSecondsLampO


berlinClockStateSecondsLampVariants : List BerlinClockStateSecondsLamp
berlinClockStateSecondsLampVariants =
    [ BerlinClockStateSecondsLampY
    , BerlinClockStateSecondsLampO
    ]


type BerlinClockStateFiveHoursRow
    = BerlinClockStateFiveHoursRowR
    | BerlinClockStateFiveHoursRowO


berlinClockStateFiveHoursRowVariants : List BerlinClockStateFiveHoursRow
berlinClockStateFiveHoursRowVariants =
    [ BerlinClockStateFiveHoursRowR
    , BerlinClockStateFiveHoursRowO
    ]


type BerlinClockStateSingleHoursRow
    = BerlinClockStateSingleHoursRowR
    | BerlinClockStateSingleHoursRowO


berlinClockStateSingleHoursRowVariants : List BerlinClockStateSingleHoursRow
berlinClockStateSingleHoursRowVariants =
    [ BerlinClockStateSingleHoursRowR
    , BerlinClockStateSingleHoursRowO
    ]


type BerlinClockStateFiveMinutesRow
    = BerlinClockStateFiveMinutesRowY
    | BerlinClockStateFiveMinutesRowR
    | BerlinClockStateFiveMinutesRowO


berlinClockStateFiveMinutesRowVariants : List BerlinClockStateFiveMinutesRow
berlinClockStateFiveMinutesRowVariants =
    [ BerlinClockStateFiveMinutesRowY
    , BerlinClockStateFiveMinutesRowR
    , BerlinClockStateFiveMinutesRowO
    ]


type BerlinClockStateSingleMinutesRow
    = BerlinClockStateSingleMinutesRowY
    | BerlinClockStateSingleMinutesRowO


berlinClockStateSingleMinutesRowVariants : List BerlinClockStateSingleMinutesRow
berlinClockStateSingleMinutesRowVariants =
    [ BerlinClockStateSingleMinutesRowY
    , BerlinClockStateSingleMinutesRowO
    ]


type alias TimeResponse =
    { hour : Maybe Int
    , minute : Maybe Int
    , second : Maybe Int
    }


-- ENCODER


encodeBerlinClockState : BerlinClockState -> Json.Encode.Value
encodeBerlinClockState =
    encodeObject << encodeBerlinClockStatePairs


encodeBerlinClockStateWithTag : ( String, String ) -> BerlinClockState -> Json.Encode.Value
encodeBerlinClockStateWithTag (tagField, tag) model =
    encodeObject (encodeBerlinClockStatePairs model ++ [ encode tagField Json.Encode.string tag ])


encodeBerlinClockStatePairs : BerlinClockState -> List EncodedField
encodeBerlinClockStatePairs model =
    let
        pairs =
            [ maybeEncode "secondsLamp" encodeBerlinClockStateSecondsLamp model.secondsLamp
            , maybeEncode "fiveHoursRow" (Json.Encode.list encodeBerlinClockStateFiveHoursRow) model.fiveHoursRow
            , maybeEncode "singleHoursRow" (Json.Encode.list encodeBerlinClockStateSingleHoursRow) model.singleHoursRow
            , maybeEncode "fiveMinutesRow" (Json.Encode.list encodeBerlinClockStateFiveMinutesRow) model.fiveMinutesRow
            , maybeEncode "singleMinutesRow" (Json.Encode.list encodeBerlinClockStateSingleMinutesRow) model.singleMinutesRow
            ]
    in
    pairs

stringFromBerlinClockStateSecondsLamp : BerlinClockStateSecondsLamp -> String
stringFromBerlinClockStateSecondsLamp model =
    case model of
        BerlinClockStateSecondsLampY ->
            "Y"

        BerlinClockStateSecondsLampO ->
            "O"


encodeBerlinClockStateSecondsLamp : BerlinClockStateSecondsLamp -> Json.Encode.Value
encodeBerlinClockStateSecondsLamp =
    Json.Encode.string << stringFromBerlinClockStateSecondsLamp


stringFromBerlinClockStateFiveHoursRow : BerlinClockStateFiveHoursRow -> String
stringFromBerlinClockStateFiveHoursRow model =
    case model of
        BerlinClockStateFiveHoursRowR ->
            "R"

        BerlinClockStateFiveHoursRowO ->
            "O"


intFromBerlinClockStateFiveHoursRow : BerlinClockStateFiveHoursRow -> Int
intFromBerlinClockStateFiveHoursRow model =
    case model of
        BerlinClockStateFiveHoursRowR ->
            0

        BerlinClockStateFiveHoursRowO ->
            1


encodeBerlinClockStateFiveHoursRow : BerlinClockStateFiveHoursRow -> Json.Encode.Value
encodeBerlinClockStateFiveHoursRow =
    Json.Encode.int << intFromBerlinClockStateFiveHoursRow


stringFromBerlinClockStateSingleHoursRow : BerlinClockStateSingleHoursRow -> String
stringFromBerlinClockStateSingleHoursRow model =
    case model of
        BerlinClockStateSingleHoursRowR ->
            "R"

        BerlinClockStateSingleHoursRowO ->
            "O"


intFromBerlinClockStateSingleHoursRow : BerlinClockStateSingleHoursRow -> Int
intFromBerlinClockStateSingleHoursRow model =
    case model of
        BerlinClockStateSingleHoursRowR ->
            0

        BerlinClockStateSingleHoursRowO ->
            1


encodeBerlinClockStateSingleHoursRow : BerlinClockStateSingleHoursRow -> Json.Encode.Value
encodeBerlinClockStateSingleHoursRow =
    Json.Encode.int << intFromBerlinClockStateSingleHoursRow


stringFromBerlinClockStateFiveMinutesRow : BerlinClockStateFiveMinutesRow -> String
stringFromBerlinClockStateFiveMinutesRow model =
    case model of
        BerlinClockStateFiveMinutesRowY ->
            "Y"

        BerlinClockStateFiveMinutesRowR ->
            "R"

        BerlinClockStateFiveMinutesRowO ->
            "O"


intFromBerlinClockStateFiveMinutesRow : BerlinClockStateFiveMinutesRow -> Int
intFromBerlinClockStateFiveMinutesRow model =
    case model of
        BerlinClockStateFiveMinutesRowY ->
            0

        BerlinClockStateFiveMinutesRowR ->
            1

        BerlinClockStateFiveMinutesRowO ->
            2


encodeBerlinClockStateFiveMinutesRow : BerlinClockStateFiveMinutesRow -> Json.Encode.Value
encodeBerlinClockStateFiveMinutesRow =
    Json.Encode.int << intFromBerlinClockStateFiveMinutesRow


stringFromBerlinClockStateSingleMinutesRow : BerlinClockStateSingleMinutesRow -> String
stringFromBerlinClockStateSingleMinutesRow model =
    case model of
        BerlinClockStateSingleMinutesRowY ->
            "Y"

        BerlinClockStateSingleMinutesRowO ->
            "O"


intFromBerlinClockStateSingleMinutesRow : BerlinClockStateSingleMinutesRow -> Int
intFromBerlinClockStateSingleMinutesRow model =
    case model of
        BerlinClockStateSingleMinutesRowY ->
            0

        BerlinClockStateSingleMinutesRowO ->
            1


encodeBerlinClockStateSingleMinutesRow : BerlinClockStateSingleMinutesRow -> Json.Encode.Value
encodeBerlinClockStateSingleMinutesRow =
    Json.Encode.int << intFromBerlinClockStateSingleMinutesRow



encodeTimeResponse : TimeResponse -> Json.Encode.Value
encodeTimeResponse =
    encodeObject << encodeTimeResponsePairs


encodeTimeResponseWithTag : ( String, String ) -> TimeResponse -> Json.Encode.Value
encodeTimeResponseWithTag (tagField, tag) model =
    encodeObject (encodeTimeResponsePairs model ++ [ encode tagField Json.Encode.string tag ])


encodeTimeResponsePairs : TimeResponse -> List EncodedField
encodeTimeResponsePairs model =
    let
        pairs =
            [ maybeEncode "hour" Json.Encode.int model.hour
            , maybeEncode "minute" Json.Encode.int model.minute
            , maybeEncode "second" Json.Encode.int model.second
            ]
    in
    pairs


-- DECODER


berlinClockStateDecoder : Json.Decode.Decoder BerlinClockState
berlinClockStateDecoder =
    Json.Decode.succeed BerlinClockState
        |> maybeDecode "secondsLamp" berlinClockStateSecondsLampDecoder Nothing
        |> maybeDecode "fiveHoursRow" (Json.Decode.list berlinClockStateFiveHoursRowDecoder) Nothing
        |> maybeDecode "singleHoursRow" (Json.Decode.list berlinClockStateSingleHoursRowDecoder) Nothing
        |> maybeDecode "fiveMinutesRow" (Json.Decode.list berlinClockStateFiveMinutesRowDecoder) Nothing
        |> maybeDecode "singleMinutesRow" (Json.Decode.list berlinClockStateSingleMinutesRowDecoder) Nothing


berlinClockStateSecondsLampDecoder : Json.Decode.Decoder BerlinClockStateSecondsLamp
berlinClockStateSecondsLampDecoder =
    Json.Decode.string
        |> Json.Decode.andThen
            (\value ->
                case value of
                    "Y" ->
                        Json.Decode.succeed BerlinClockStateSecondsLampY

                    "O" ->
                        Json.Decode.succeed BerlinClockStateSecondsLampO

                    other ->
                        Json.Decode.fail <| "Unknown type: " ++ other
            )



berlinClockStateFiveHoursRowDecoder : Json.Decode.Decoder BerlinClockStateFiveHoursRow
berlinClockStateFiveHoursRowDecoder =
    Json.Decode.string
        |> Json.Decode.andThen
            (\value ->
                case value of
                    "R" ->
                        Json.Decode.succeed BerlinClockStateFiveHoursRowR

                    "O" ->
                        Json.Decode.succeed BerlinClockStateFiveHoursRowO

                    other ->
                        Json.Decode.fail <| "Unknown type: " ++ other
            )



berlinClockStateSingleHoursRowDecoder : Json.Decode.Decoder BerlinClockStateSingleHoursRow
berlinClockStateSingleHoursRowDecoder =
    Json.Decode.string
        |> Json.Decode.andThen
            (\value ->
                case value of
                    "R" ->
                        Json.Decode.succeed BerlinClockStateSingleHoursRowR

                    "O" ->
                        Json.Decode.succeed BerlinClockStateSingleHoursRowO

                    other ->
                        Json.Decode.fail <| "Unknown type: " ++ other
            )



berlinClockStateFiveMinutesRowDecoder : Json.Decode.Decoder BerlinClockStateFiveMinutesRow
berlinClockStateFiveMinutesRowDecoder =
    Json.Decode.string
        |> Json.Decode.andThen
            (\value ->
                case value of
                    "Y" ->
                        Json.Decode.succeed BerlinClockStateFiveMinutesRowY

                    "R" ->
                        Json.Decode.succeed BerlinClockStateFiveMinutesRowR

                    "O" ->
                        Json.Decode.succeed BerlinClockStateFiveMinutesRowO

                    other ->
                        Json.Decode.fail <| "Unknown type: " ++ other
            )



berlinClockStateSingleMinutesRowDecoder : Json.Decode.Decoder BerlinClockStateSingleMinutesRow
berlinClockStateSingleMinutesRowDecoder =
    Json.Decode.string
        |> Json.Decode.andThen
            (\value ->
                case value of
                    "Y" ->
                        Json.Decode.succeed BerlinClockStateSingleMinutesRowY

                    "O" ->
                        Json.Decode.succeed BerlinClockStateSingleMinutesRowO

                    other ->
                        Json.Decode.fail <| "Unknown type: " ++ other
            )



timeResponseDecoder : Json.Decode.Decoder TimeResponse
timeResponseDecoder =
    Json.Decode.succeed TimeResponse
        |> maybeDecode "hour" Json.Decode.int Nothing
        |> maybeDecode "minute" Json.Decode.int Nothing
        |> maybeDecode "second" Json.Decode.int Nothing




-- HELPER


type alias EncodedField =
    Maybe ( String, Json.Encode.Value )


encodeObject : List EncodedField -> Json.Encode.Value
encodeObject =
    Json.Encode.object << List.filterMap identity


encode : String -> (a -> Json.Encode.Value) -> a -> EncodedField
encode key encoder value =
    Just ( key, encoder value )


encodeNullable : String -> (a -> Json.Encode.Value) -> Maybe a -> EncodedField
encodeNullable key encoder value =
    Just ( key, Maybe.withDefault Json.Encode.null (Maybe.map encoder value) )


maybeEncode : String -> (a -> Json.Encode.Value) -> Maybe a -> EncodedField
maybeEncode key encoder =
    Maybe.map (Tuple.pair key << encoder)


maybeEncodeNullable : String -> (a -> Json.Encode.Value) -> Maybe a -> EncodedField
maybeEncodeNullable =
    encodeNullable


decode : String -> Json.Decode.Decoder a -> Json.Decode.Decoder (a -> b) -> Json.Decode.Decoder b
decode key decoder =
    decodeChain (Json.Decode.field key decoder)


decodeLazy : (a -> c) -> String -> Json.Decode.Decoder a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
decodeLazy f key decoder =
    decodeChainLazy f (Json.Decode.field key decoder)


decodeNullable : String -> Json.Decode.Decoder a -> Json.Decode.Decoder (Maybe a -> b) -> Json.Decode.Decoder b
decodeNullable key decoder =
    decodeChain (maybeField key decoder Nothing)


decodeNullableLazy : (Maybe a -> c) -> String -> Json.Decode.Decoder a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
decodeNullableLazy f key decoder =
    decodeChainLazy f (maybeField key decoder Nothing)


maybeDecode : String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (Maybe a -> b) -> Json.Decode.Decoder b
maybeDecode key decoder fallback =
    -- let's be kind to null-values as well
    decodeChain (maybeField key decoder fallback)


maybeDecodeLazy : (Maybe a -> c) -> String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
maybeDecodeLazy f key decoder fallback =
    -- let's be kind to null-values as well
    decodeChainLazy f (maybeField key decoder fallback)


maybeDecodeNullable : String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (Maybe a -> b) -> Json.Decode.Decoder b
maybeDecodeNullable key decoder fallback =
    decodeChain (maybeField key decoder fallback)


maybeDecodeNullableLazy : (Maybe a -> c) -> String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
maybeDecodeNullableLazy f key decoder fallback =
    decodeChainLazy f (maybeField key decoder fallback)


maybeField : String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (Maybe a)
maybeField key decoder fallback =
    let
        fieldDecoder =
            Json.Decode.field key Json.Decode.value

        valueDecoder =
            Json.Decode.oneOf [ Json.Decode.map Just decoder, Json.Decode.null fallback ]

        decodeObject rawObject =
            case Json.Decode.decodeValue fieldDecoder rawObject of
                Ok rawValue ->
                    case Json.Decode.decodeValue valueDecoder rawValue of
                        Ok value ->
                            Json.Decode.succeed value

                        Err error ->
                            Json.Decode.fail (Json.Decode.errorToString error)

                Err _ ->
                    Json.Decode.succeed fallback
    in
    Json.Decode.value
        |> Json.Decode.andThen decodeObject


decodeChain : Json.Decode.Decoder a -> Json.Decode.Decoder (a -> b) -> Json.Decode.Decoder b
decodeChain =
    Json.Decode.map2 (|>)


decodeChainLazy : (a -> c) -> Json.Decode.Decoder a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
decodeChainLazy f =
    decodeChain << Json.Decode.map f